name: Test Sample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Java Version
        run: java -version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Test
        run: ./gradlew test

